[tool.poetry]
name = "any-parser-rt"
version = "0.0.2"
description = ""
authors = ["Rachel Hu <goldpiggy@berkeley.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
